os: linux
language: python
python: "3.8"
dist: focal
compiler:
  - gcc
install:
  - pip install conan
# Automatic detection of your arch, compiler, etc.
  - conan user
  - conan profile update settings.compiler.libcxx=libstdc++11 default
script:
  - conan install . -if build
  - cmake . -Bbuild -G "Unix Makefiles"
  - cmake --build build
  - cd build
  - ctest .
  - cd ..